name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_DB: lab5db
          POSTGRES_USER: lab5user
          POSTGRES_PASSWORD: lab5pass
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U lab5user -d lab5db"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    env:
      DB_HOST: localhost
      DB_PORT: 5432
      DB_NAME: lab5db
      DB_USER: lab5user
      DB_PASS: lab5pass
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Wait for PostgreSQL to be ready
        run: |
          echo "Waiting for PostgreSQL..."
          for i in {1..10}; do
            pg_isready -h localhost -p 5432 -U lab5user && break
            sleep 1
          done

      - name: Run model sync
        run: node src/sync.js

      - name: Run tests
        run: npm test

      - name: Lint code
        run: npm run lint

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/lab5-log430:latest .

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/lab5-log430:latest 

